name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run Maven Tests
      working-directory: ./where-is-my-exam
      run: mvn test

  frontend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ./exam-finder-frontend/package-lock.json
    - name: Install dependencies
      working-directory: ./exam-finder-frontend
      run: npm ci
    - name: Run Vitest Tests
      working-directory: ./exam-finder-frontend
      run: npm run test
